python -m src.train_lora \
   --model_name_or_path ./ckpts/vicuna-7b \
    --data_path ./data/sharegpt-train-10k-instruct.json \
    --output_dir ./ckpts/vicuna-response-length-perception-module-30 \
    --bf16 True \
    --tf32 True \
    --evaluation_strategy "no" \
    --lazy_preprocess True \
    --save_strategy "steps" \
    --save_steps 500 \
    --save_total_limit 1 \
    --logging_steps 1 \
    --num_train_epochs 30 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 16 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine"
